export const REFRESH_ROOMS = 'REFRESH_ROOMS';

export const LISTEN_ROOM_MESSAGES = 'GET_ROOM_MESSAGES';
export const CHANGE_ROOM = 'CHANGE_ROOM';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';