export const REFRESH_ROOMS = 'REFRESH_ROOMS';

export const LISTEN_ROOM_MESSAGES = 'GET_ROOM_MESSAGES';
export const CHANGE_ROOM = 'CHANGE_ROOM';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const CLEAR_NEW_USER = 'CLEAR_NEW_USER';
